apiVersion: batch/v1
kind: Cronjob
metadata:
  name: mycronjob
  namespace: my-ns
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name:
              image:
                command:
                - /bin/sh
                - "-c"
                - date; echo hello world from kubernets
            restartPolicy: Never
